[package]
name = "tca"
version = "0.1.0"
edition = "2021"

[dependencies]
anyhow = "1.0.86"
async-trait = "0.1.81"
futures = "0.3.30"
lock_api = "0.4.12"
log = "0.4.22"
parking_lot = "0.12.3"
tokio = { version = "1.39.2", features = ["full"] }
